[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mongodb/mongo-go-driver"
  version = "0.3.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"
